"""Tiered memory tests. Output is written to logs/memory_test.log (masked).

1. Cross-session (long-term, LangMem + SQLite store): session 1 runs in a SEPARATE OS PROCESS and
   states a fact; that process exits; a NEW graph instance in this process opens the same on-disk
   stores and runs session 2 on a NEW thread for the same customer, which must recall the fact.
   A different customer asking the same question must not.
2. Within-session (short-term, checkpointer thread): a fact stated in turn 1 is used in turn 3,
   after history compression has removed turn 1 from the message window.

No API key needed: Gemini is disabled (rules/templates), so results are deterministic.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import pytest

from src.config import MEMORY_TEST_LOG, ROOT_DIR, SAMPLE_CONTACTS_PATH
from src.context import compress
from src.guardrails.pii import mask, mask_customer_id
from tests.memory_driver import run_session

FACT_TEXT = ("I'm starting to work from home full time next month, so I'll be doing lots of video calls. "
             "What's my current data allowance?")
RECALL_TEXT = "Hi again. Given what I told you last time about my work situation, is my current plan still right for me?"


def _customers() -> tuple[str, str]:
    contacts = {json.loads(l)["scenario"]: json.loads(l) for l in SAMPLE_CONTACTS_PATH.read_text().splitlines()}
    return contacts["memory_visit_1"]["customer_id"], contacts["cancellation_at_risk_within_threshold"]["customer_id"]


class MemoryLog:
    """Append-only, masked, human-readable evidence log."""

    def __init__(self, path: Path):
        self.path = path

    def line(self, text: str = "") -> None:
        with self.path.open("a", encoding="utf-8") as fh:
            fh.write(mask(text, amounts=False) + "\n")

    def section(self, title: str) -> None:
        self.line()
        self.line("=" * 88)
        self.line(title)
        self.line("=" * 88)

    def check(self, name: str, ok: bool, detail: str = "") -> bool:
        self.line(f"  [{'PASS' if ok else 'FAIL'}] {name}" + (f" -- {detail}" if detail else ""))
        return ok


@pytest.fixture(scope="module")
def mlog() -> MemoryLog:
    MEMORY_TEST_LOG.parent.mkdir(parents=True, exist_ok=True)
    MEMORY_TEST_LOG.write_text("")
    log = MemoryLog(MEMORY_TEST_LOG)
    log.line(f"memory_test.log -- generated by tests/test_memory_persistence.py at "
             f"{datetime.now(timezone.utc).isoformat(timespec='seconds')}")
    log.line("Engine: rules/templates (Gemini disabled for determinism); identifiers masked.")
    return log


def _rel(p: Path) -> str:
    return f"<tmp>/{p.name}"


def _dump_turn(log: MemoryLog, label: str, turn: dict) -> None:
    log.line(f"  {label}: intent={turn['intent']} outcome={turn['outcome']} messages_in_thread={turn['message_count']}")
    log.line(f"    context_stats: {turn['context_stats']}")
    if turn["session_facts"]:
        log.line(f"    session_facts: {turn['session_facts']}")
    for m in turn["memories"]:
        log.line(f"    recalled[{m['selected_by']}] ({m['kind']}, score={m['score']}): {m['content']}")
    for w in turn["memory_written"]:
        log.line(f"    wrote ({w['kind']}): {w['content']}")
    log.line(f"    reply: {turn['reply']}")


@pytest.mark.asyncio
async def test_cross_session_recall_after_process_restart(tmp_path: Path, mlog: MemoryLog):
    customer, other_customer = _customers()
    checkpoints, memory_db, logs = tmp_path / "checkpoints.db", tmp_path / "memory_store.db", tmp_path / "logs"
    mlog.section("TEST 1: cross-session recall (long-term memory survives process exit)")
    mlog.line(f"customer={mask_customer_id(customer)} control_customer={mask_customer_id(other_customer)}")
    mlog.line(f"stores: checkpoints={_rel(checkpoints)} long_term={_rel(memory_db)} (LangMem over AsyncSqliteStore)")

    # --- Session 1 in a separate process ------------------------------------------
    proc = subprocess.run(
        [sys.executable, "-m", "tests.memory_driver", "--checkpoints", str(checkpoints), "--memory", str(memory_db),
         "--logs", str(logs), "--customer", customer, "--session", "SES-MEMTEST-1", "--text", FACT_TEXT],
        cwd=ROOT_DIR, capture_output=True, text=True, timeout=300,
    )
    assert proc.returncode == 0, proc.stderr[-2000:]
    s1 = json.loads(next(l for l in proc.stdout.splitlines() if l.startswith("RESULT_JSON="))[len("RESULT_JSON="):])
    mlog.line(f"\nSession 1: pid={s1['pid']} thread=SES-MEMTEST-1 run_id={s1['run_id']} (process exited rc=0)")
    mlog.line(f"  customer said: {FACT_TEXT}")
    _dump_turn(mlog, "turn 1", s1["turns"][0])

    # --- Session 2: new graph instance, new thread, same customer --------------------
    s2 = await run_session(checkpoints=checkpoints, memory_path=memory_db, logs_dir=logs, customer_id=customer,
                           session_id="SES-MEMTEST-2", turns=[RECALL_TEXT])
    t2 = s2["turns"][0]
    mlog.line(f"\nSession 2: pid={s2['pid']} thread=SES-MEMTEST-2 run_id={s2['run_id']} (new graph instance)")
    mlog.line(f"  customer said: {RECALL_TEXT}")
    _dump_turn(mlog, "turn 1", t2)

    # --- Control: another customer, same question ----------------------------------
    s3 = await run_session(checkpoints=checkpoints, memory_path=memory_db, logs_dir=logs, customer_id=other_customer,
                           session_id="SES-MEMTEST-3", turns=[RECALL_TEXT])
    t3 = s3["turns"][0]
    mlog.line(f"\nControl: other customer {mask_customer_id(other_customer)} thread=SES-MEMTEST-3")
    _dump_turn(mlog, "turn 1", t3)

    mlog.line("\nAssertions:")
    written = [w["content"] for w in s1["turns"][0]["memory_written"]]
    recalled = [m["content"] for m in t2["memories"]]
    checks = [
        mlog.check("session 1 ran in a different OS process than session 2", s1["pid"] != s2["pid"],
                   f"pid {s1['pid']} vs {s2['pid']}"),
        mlog.check("session 1 wrote the work-from-home fact to long-term memory",
                   any("work from home" in w for w in written)),
        mlog.check("session 2 is a new thread: none of session 1's customer messages are in it",
                   t2["customer_texts"] == [RECALL_TEXT] and not any("work from home" in t for t in t2["customer_texts"]),
                   f"thread has {s2['thread_message_count']} messages"),
        mlog.check("session 2 recalled the fact from the long-term store", any("work from home" in r for r in recalled)),
        mlog.check("fact did not come from session 2's own session_facts",
                   not any("work from home" in f for f in t2["session_facts"])),
        mlog.check("session 2 reply uses the recalled fact",
                   "work from home" in t2["reply"] and "Last time you told me" in t2["reply"]),
        mlog.check("control customer recalls nothing from another customer's memory",
                   not t3["memories"] and "work from home" not in t3["reply"]),
    ]
    mlog.line(f"RESULT test_cross_session_recall_after_process_restart: {'PASS' if all(checks) else 'FAIL'}")
    assert all(checks), "see logs/memory_test.log"


@pytest.mark.asyncio
async def test_within_session_fact_used_after_compression(tmp_path: Path, mlog: MemoryLog, monkeypatch):
    customer = json.loads(SAMPLE_CONTACTS_PATH.read_text().splitlines()[0])["customer_id"]  # CT-0001's caller
    monkeypatch.setattr(compress, "CONTEXT_TOKEN_BUDGET", 150)
    monkeypatch.setattr(compress, "KEEP_LAST_MESSAGES", 2)
    turns = [
        "I mostly use my data for video calls when I work from home.",
        "Also, can you explain the charges on my latest bill?",
        "Which plan would suit me best?",
    ]
    mlog.section("TEST 2: within-session recall (fact from turn 1 used in turn 3, after compression)")
    mlog.line(f"customer={mask_customer_id(customer)} thread=SES-MEMTEST-W  budget=150 tokens, keep last 2 messages")
    s = await run_session(checkpoints=tmp_path / "checkpoints.db", memory_path=tmp_path / "memory_store.db",
                          logs_dir=tmp_path / "logs", customer_id=customer, session_id="SES-MEMTEST-W", turns=turns)
    for i, (text, t) in enumerate(zip(turns, s["turns"]), start=1):
        mlog.line(f"\n  customer turn {i}: {text}")
        _dump_turn(mlog, f"turn {i}", t)
    t3 = s["turns"][2]
    mlog.line(f"\n  running summary at turn 3:\n    " + (t3["summary"] or "(none)").replace("\n", "\n    "))

    mlog.line("\nAssertions:")
    checks = [
        mlog.check("turn 1 fact captured in session_facts",
                   any("video calls" in f for f in s["turns"][0]["session_facts"])),
        mlog.check("history was compressed before turn 3", (t3["context_stats"] or {}).get("compressed_messages", 0) > 0,
                   f"{t3['context_stats']}"),
        mlog.check("turn 1's customer message is no longer in the message window at turn 3",
                   not any("video calls" in m for m in t3["customer_texts"]),
                   f"window holds {t3['message_count']} messages; customer turns: {t3['customer_texts']}"),
        mlog.check("turn 3 is a plan question", t3["intent"] == "plan_change"),
        mlog.check("turn 3 reply uses the turn-1 fact", "video calls" in t3["reply"] and "You mentioned" in t3["reply"]),
    ]
    mlog.line(f"RESULT test_within_session_fact_used_after_compression: {'PASS' if all(checks) else 'FAIL'}")
    assert all(checks), "see logs/memory_test.log"
