"""Cost / latency dashboard.

1. reports/dashboard_data.csv  - one row per span from traces/phoenix_spans.parquet (same normalisation
                                 as scripts/golden_signals.py: class, latency, tokens, cost, run, agent)
2. reports/dashboard_charts.png - matplotlib panel drawn ONLY from that CSV: latency by span class,
                                 tool latency, tokens per run, cost per run
3. reports/dashboard.png       - automated Playwright screenshot of the Phoenix UI project view on
                                 localhost:6006 (in-process app over the persisted PHOENIX_WORKING_DIR)

Run: python -m scripts.dashboard [--no-screenshot]   (first time: playwright install chromium)
"""

from __future__ import annotations

import argparse
import asyncio
import sys

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import pandas as pd  # noqa: E402

from scripts.golden_signals import span_table  # noqa: E402
from src.config import DASHBOARD_CSV_PATH, DASHBOARD_PNG_PATH, PHOENIX_SPANS_PATH, REPORTS_DIR, ROOT_DIR, settings  # noqa: E402

CHARTS_PATH = REPORTS_DIR / "dashboard_charts.png"
CLASS_COLORS = {"thinking": "#7b61ff", "acting": "#2a9d8f", "tool": "#e76f51", "other": "#8d99ae"}


def write_csv() -> pd.DataFrame:
    t = span_table(pd.read_parquet(PHOENIX_SPANS_PATH))
    t = t.drop(columns=["tool_status"]).sort_values("start_time")
    t.to_csv(DASHBOARD_CSV_PATH, index=False)
    print(f"{DASHBOARD_CSV_PATH.relative_to(ROOT_DIR)}: {len(t)} spans x {len(t.columns)} columns")
    return t


def write_charts() -> None:
    d = pd.read_csv(DASHBOARD_CSV_PATH)  # the chart is drawn from the CSV, not from memory
    fig, axes = plt.subplots(2, 2, figsize=(14, 9))
    fig.suptitle(f"Retention copilot: cost & latency ({settings.phoenix_project_name}, "
                 f"{d['run_id'].nunique()} runs, {len(d)} spans)", fontsize=13)

    ax = axes[0, 0]
    cls = d[d["span_class"] != "other"].groupby("span_class")["latency_ms"]
    q = pd.DataFrame({"p50": cls.quantile(0.5), "p95": cls.quantile(0.95)}).reindex(["thinking", "acting", "tool"])
    q.plot.bar(ax=ax, color=["#264653", "#e9c46a"], rot=0)
    ax.set_title("Latency by span class (ms)")
    ax.set_ylabel("ms")
    if pd.isna(q.loc["thinking", "p50"]):
        ax.text(0, 0, "no LLM spans", ha="center", va="bottom", fontsize=9, color="#7b61ff")

    ax = axes[0, 1]
    tools = d[d["span_kind"] == "TOOL"].groupby("name")["latency_ms"].median().sort_values()
    tools.plot.barh(ax=ax, color=CLASS_COLORS["tool"])
    ax.set_title("Tool latency p50 (ms)")
    ax.set_xlabel("ms")

    runs = d.dropna(subset=["run_id"]).groupby("contact_id").agg(
        prompt=("prompt_tokens", "sum"), completion=("completion_tokens", "sum"), cost=("cost_usd", "sum"),
        e2e=("latency_ms", lambda s: s[d.loc[s.index, "name"] == "copilot.turn"].sum()))
    ax = axes[1, 0]
    runs[["prompt", "completion"]].plot.bar(ax=ax, stacked=True, color=["#457b9d", "#a8dadc"], rot=45)
    ax.set_title("Tokens per run (LLM spans)")
    if runs[["prompt", "completion"]].to_numpy().sum() == 0:
        ax.text(0.5, 0.5, "0 tokens: this run used rules/templates\n(no Gemini calls traced)",
                transform=ax.transAxes, ha="center", va="center", fontsize=10, color="#555")

    ax = axes[1, 1]
    ax2 = ax.twinx()
    runs["e2e"].plot.bar(ax=ax, color=CLASS_COLORS["acting"], alpha=0.6, rot=45, label="end-to-end ms")
    ax2.plot(range(len(runs)), runs["cost"], color="#d62828", marker="o", label="cost USD")
    ax.set_title("End-to-end latency (bars, ms) and cost (line, USD) per run")
    ax.set_ylabel("ms")
    ax2.set_ylabel("USD")
    fig.text(0.01, 0.005, f"source: {DASHBOARD_CSV_PATH.relative_to(ROOT_DIR)} <- "
             f"{PHOENIX_SPANS_PATH.relative_to(ROOT_DIR)} | generated by scripts/dashboard.py", fontsize=8, color="#666")
    fig.tight_layout(rect=(0, 0.02, 1, 0.96))
    fig.savefig(CHARTS_PATH, dpi=110)
    print(f"{CHARTS_PATH.relative_to(ROOT_DIR)} written")


async def screenshot() -> bool:
    from phoenix.client import Client
    from playwright.async_api import async_playwright

    from src.observability import tracing

    url = tracing.launch_phoenix()
    project = Client(base_url=url).projects.get(project_name=settings.phoenix_project_name)
    target = f"{url}/projects/{project['id']}"
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        page = await browser.new_page(viewport={"width": 1600, "height": 1000})
        await page.goto(target, wait_until="networkidle", timeout=60_000)
        await page.wait_for_timeout(4000)  # let the span table and charts render
        await page.screenshot(path=str(DASHBOARD_PNG_PATH), full_page=False)
        await browser.close()
    print(f"{DASHBOARD_PNG_PATH.relative_to(ROOT_DIR)}: Phoenix UI screenshot of {target}")
    return True


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-screenshot", action="store_true")
    a = ap.parse_args()
    write_csv()
    write_charts()
    if a.no_screenshot:
        return 0
    try:
        return 0 if asyncio.run(screenshot()) else 1
    except Exception as exc:  # never fake a screenshot
        print(f"Phoenix screenshot FAILED ({type(exc).__name__}: {str(exc)[:200]}); dashboard.png not written")
        return 1


if __name__ == "__main__":
    sys.exit(main())
